services:
  - type: web
    name: ev-charging-app
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: DATABASE_URL
        value: stationData.db
      - key: SECRET_KEY
        value: your-secret-key-here