services:
  - type: web
    name: ev-charging-app
    runtime: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.9"